version: '3'
services: 
  node_service:
    restart: always
    image: n1:latest
    #command: node console.log('hello world')  
    ports:
      - "80:8080"
      # from port 80 to port 8080
    depends_on: 
      - mongo_service
  mongo_service:
    restart: always
    image: mongo:latest
    volumes:
      - /Users/msant/d/tmp/db:/data/db
    ports:
      - "27017:27017"
